<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Estimand-Estimator Alignment in Time-to-Event Safety Analyses</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="draft-estimands-results-outline_files/libs/clipboard/clipboard.min.js"></script>
<script src="draft-estimands-results-outline_files/libs/quarto-html/quarto.js"></script>
<script src="draft-estimands-results-outline_files/libs/quarto-html/popper.min.js"></script>
<script src="draft-estimands-results-outline_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="draft-estimands-results-outline_files/libs/quarto-html/anchor.min.js"></script>
<link href="draft-estimands-results-outline_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="draft-estimands-results-outline_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="draft-estimands-results-outline_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="draft-estimands-results-outline_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="draft-estimands-results-outline_files/libs/bootstrap/bootstrap-1bc8a17f135ab3d594c857e9f48e611b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Estimand-Estimator Alignment in Time-to-Event Safety Analyses</h1>
<p class="subtitle lead">A hepatitis B case study with longitudinal targeted learning</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<!--
TODO(Joy): verify exact variable mapping from DGP.R to chapter notation.
TODO(Joy): refine hepatitis B DGP parameters to match realistic renal-failure
  incidence in tenofovir vs entecavir from the literature.
TODO(Joy): decide whether to include the time-dependent Cox model in the
  main presentation or relegate it to an appendix.
-->
<section id="estimand-estimator-alignment-in-time-to-event-safety-analyses" class="level1">
<h1>Estimand-Estimator Alignment in Time-to-Event Safety Analyses</h1>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>In post-marketing safety studies, the question “Does this drug increase the risk of adverse events?” cannot be answered without first specifying how intercurrent events—treatment switching, discontinuation, death from other causes—are handled. The ICH E9(R1) addendum formalises this requirement through the estimand framework: five elements (population, treatment, outcome, intercurrent events, and strategy) must be specified before analysis. Different strategies for handling the same intercurrent event define different estimands, and different estimands require compatible estimators.</p>
<p>This chapter examines whether conventional regression analyses succeed in estimating the stated estimand when treatment switching is present. We focus on two estimands—the treatment-policy and hypothetical no-switch strategies—because they most clearly illustrate the consequences of using a mismatched estimator. Three additional ICH E9(R1) strategies (while-on-treatment, composite, and principal stratum) are defined for context and included in the simulation, but receive less detailed treatment. A simulated hepatitis B safety study provides the running example throughout.</p>
<p>The analysis follows the causal roadmap for real-world evidence generation (Dang et al.&nbsp;2023; Petersen 2014), which proceeds through defining the causal question, specifying a causal model, assessing identifiability, defining the statistical estimand, choosing an estimator, and conducting sensitivity analyses. This chapter concentrates on defining estimands, diagnosing empirical support, and comparing estimators.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survival)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="fu">here</span>(<span class="st">"DGP.R"</span>))</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="fu">here</span>(<span class="st">"R"</span>, <span class="st">"helpers.R"</span>))</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="fu">here</span>(<span class="st">"R"</span>, <span class="st">"support_diagnostics.R"</span>))</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>cache_files <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">here</span>(<span class="st">"results"</span>, <span class="st">"lmtp_main.rds"</span>),</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">here</span>(<span class="st">"results"</span>, <span class="st">"support_estimation.rds"</span>),</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">here</span>(<span class="st">"results"</span>, <span class="st">"sim_study_main.rds"</span>),</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">here</span>(<span class="st">"results"</span>, <span class="st">"sim_results"</span>, <span class="st">"ground_truth.rds"</span>)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>missing <span class="ot">&lt;-</span> cache_files[<span class="sc">!</span><span class="fu">file.exists</span>(cache_files)]</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">length</span>(missing) <span class="sc">&gt;</span> <span class="dv">0</span>) {</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">warning</span>(<span class="st">"Missing cached results. Run R/run_cached_analyses.R first:</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>          <span class="fu">paste</span>(<span class="st">" "</span>, <span class="fu">basename</span>(missing), <span class="at">collapse =</span> <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>))</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="the-hepatitis-b-safety-example" class="level2">
<h2 class="anchored" data-anchor-id="the-hepatitis-b-safety-example">The Hepatitis B Safety Example</h2>
<p>We use a simulated post-marketing safety study comparing two hepatitis B antiviral regimens for the risk of renal failure. The setting draws on concerns about nephrotoxicity in tenofovir-containing regimens relative to entecavir-based alternatives.</p>
<p>The simulated cohort includes an active regimen (analogous to tenofovir) and a comparator (analogous to entecavir), with confounded treatment assignment driven by baseline CKD, cirrhosis, and age. The primary intercurrent event is informative treatment switching: patients on the active regimen who develop early renal signals may switch to the comparator. Because CKD drives both switching and renal failure, switching is informative—the patients who switch are those at greatest risk.</p>
<p>Baseline confounders include demographics (age, sex, race), comorbidities (CKD, diabetes, hypertension, cirrhosis, heart failure), and co-medications (NSAIDs, ACE/ARBs, statins). The outcome is time to renal failure observed over a 180-day risk window.</p>
<!-- TODO(Joy): add one paragraph with real-data references if a project-approved
     example from the hepatitis B nephrotoxicity literature is available. -->
</section>
<section id="the-data-generating-process" class="level2">
<h2 class="anchored" data-anchor-id="the-data-generating-process">The Data-Generating Process</h2>
<p>The function <code>generate_hep_data()</code> simulates the cohort. Key components are summarised in the table below.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Component</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Treatment assignment</strong></td>
<td>Active vs comparator, confounded by CKD, cirrhosis, age; nonlinear interactions when <code>complexity=TRUE</code></td>
</tr>
<tr class="even">
<td><strong>Event process</strong></td>
<td>Piecewise exponential hazard; HR = 1.25 before day 45 and HR = 0.70 after (non-proportional hazards)</td>
</tr>
<tr class="odd">
<td><strong>Switching process</strong></td>
<td>Hazard-based informative switching driven by treatment and CKD</td>
</tr>
<tr class="even">
<td><strong>Censoring</strong></td>
<td>Dependent on baseline risk when <code>dep_censor=TRUE</code>; otherwise administrative only</td>
</tr>
</tbody>
</table>
<p>The <code>policy</code> argument controls how switching affects follow-up. Under <code>"treatment_policy"</code>, switching occurs but does not censor—subjects are followed until the event or administrative censoring regardless of switching. Under <code>"no_switch"</code>, switching is suppressed entirely, generating potential outcomes for the hypothetical world where nobody switches. Additional policies (<code>"while_on_treatment"</code>, <code>"composite"</code>, <code>"principal_stratum"</code>) are available for the remaining estimands.</p>
<!-- TODO(Joy): verify exact variable mapping from DGP.R to chapter notation -->
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2026</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">generate_hep_data</span>(</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">N           =</span> <span class="dv">10000</span>,</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">np_hazard   =</span> <span class="cn">TRUE</span>,</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">dep_censor  =</span> <span class="cn">TRUE</span>,</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">complexity  =</span> <span class="cn">TRUE</span>,</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">policy      =</span> <span class="st">"treatment_policy"</span>,</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">seed        =</span> <span class="dv">2026</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Quantity</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">N</td>
<td style="text-align: right;">1.000e+04</td>
</tr>
<tr class="even">
<td style="text-align: left;">Event rate</td>
<td style="text-align: right;">7.630e-02</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Switch rate</td>
<td style="text-align: right;">1.173e-01</td>
</tr>
<tr class="even">
<td style="text-align: left;">Switch rate (active + CKD)</td>
<td style="text-align: right;">2.256e-01</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Switch rate (comparator)</td>
<td style="text-align: right;">8.770e-02</td>
</tr>
<tr class="even">
<td style="text-align: left;">Median follow-up (days)</td>
<td style="text-align: right;">6.270e+01</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dagitty)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggdag)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>dag_safety <span class="ot">&lt;-</span> <span class="fu">dagify</span>(</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  Treatment <span class="sc">~</span> W,</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  Switch <span class="sc">~</span> Treatment <span class="sc">+</span> W,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  Censoring <span class="sc">~</span> Switch <span class="sc">+</span> W,</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>  RenalFailure <span class="sc">~</span> Treatment <span class="sc">+</span> Switch <span class="sc">+</span> W,</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">exposure =</span> <span class="st">"Treatment"</span>, <span class="at">outcome =</span> <span class="st">"RenalFailure"</span>,</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">labels =</span> <span class="fu">c</span>(<span class="at">W =</span> <span class="st">"Baseline</span><span class="sc">\n</span><span class="st">confounders</span><span class="sc">\n</span><span class="st">(CKD, age, ...)"</span>,</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>             <span class="at">Treatment =</span> <span class="st">"Treatment</span><span class="sc">\n</span><span class="st">(active vs comparator)"</span>,</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>             <span class="at">Switch =</span> <span class="st">"Regimen</span><span class="sc">\n</span><span class="st">switch"</span>,</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>             <span class="at">Censoring =</span> <span class="st">"Censoring"</span>,</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>             <span class="at">RenalFailure =</span> <span class="st">"Renal</span><span class="sc">\n</span><span class="st">failure"</span>),</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">coords =</span> <span class="fu">list</span>(</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="fu">c</span>(<span class="at">W =</span> <span class="dv">1</span>, <span class="at">Treatment =</span> <span class="dv">0</span>, <span class="at">Switch =</span> <span class="dv">1</span>, <span class="at">Censoring =</span> <span class="dv">2</span>, <span class="at">RenalFailure =</span> <span class="fl">1.5</span>),</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="fu">c</span>(<span class="at">W =</span> <span class="dv">1</span>, <span class="at">Treatment =</span> <span class="dv">0</span>, <span class="at">Switch =</span> <span class="dv">0</span>, <span class="at">Censoring =</span> <span class="dv">0</span>, <span class="at">RenalFailure =</span> <span class="sc">-</span><span class="dv">1</span>)</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a><span class="fu">ggdag</span>(dag_safety, <span class="at">text =</span> <span class="cn">FALSE</span>, <span class="at">use_labels =</span> <span class="st">"label"</span>, <span class="at">text_size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_dag</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-dag" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-dag-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="draft-estimands-results-outline_files/figure-html/fig-dag-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dag-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Causal structure. Baseline confounders (W) affect treatment, switching, censoring, and renal failure.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="five-estimand-strategies" class="level2">
<h2 class="anchored" data-anchor-id="five-estimand-strategies">Five Estimand Strategies</h2>
<p>The ICH E9(R1) addendum defines five strategies for handling intercurrent events. In a safety study where treatment switching is the primary intercurrent event, each strategy answers a different clinical question.</p>
<p><strong>Treatment-policy.</strong> What is the 180-day risk of renal failure comparing populations <em>initiated</em> on the active versus the comparator regimen, regardless of subsequent switching? The target parameter is <span class="math inline">\(\psi^{TP} = E[Y^{a=1}(180)] - E[Y^{a=0}(180)]\)</span>, where switching occurs naturally and is not intervened upon.</p>
<p><strong>Hypothetical no-switch.</strong> What <em>would</em> the 180-day risk be if no patients switched? The target is <span class="math inline">\(\psi^{HYP} = E[Y^{a=1, \text{no switch}}(180)] - E[Y^{a=0, \text{no switch}}(180)]\)</span>. Identification requires modelling the time-varying confounders that drive both switching and the outcome.</p>
<p><strong>While-on-treatment.</strong> What is the risk while patients remain on their assigned treatment? Follow-up is censored at switching, and the target conditions on not switching by 180 days. Naive estimation censors at switch time and assumes non-informative censoring; IPCW or LMTP can relax this assumption.</p>
<p><strong>Composite.</strong> What is the risk of renal failure <em>or</em> switching (whichever comes first)? Switching is absorbed into the outcome, avoiding the need to model the switching mechanism. The trade-off is that the composite conflates tolerability with safety.</p>
<p><strong>Principal stratum.</strong> What is the risk among patients who would not switch under either treatment? The target population is the latent “never-switcher” stratum, identified through joint potential switching indicators. Identification requires monotonicity or similar structural assumptions.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Strategy</th>
<th>Handling</th>
<th>Key assumption</th>
<th>Trade-off</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Treatment-policy</td>
<td>Ignore switching</td>
<td>None for switching</td>
<td>Includes post-switch outcomes</td>
</tr>
<tr class="even">
<td>Hypothetical</td>
<td>Model world without switching</td>
<td>Correct switching model</td>
<td>Requires modelling switching mechanism</td>
</tr>
<tr class="odd">
<td>While-on-treatment</td>
<td>Censor at switch</td>
<td>Non-informative censoring (or IPCW)</td>
<td>Bias if switching is informative</td>
</tr>
<tr class="even">
<td>Composite</td>
<td>Include switching in outcome</td>
<td>None for switching</td>
<td>Conflates switching and renal failure</td>
</tr>
<tr class="odd">
<td>Principal stratum</td>
<td>Restrict to never-switchers</td>
<td>Monotonicity</td>
<td>Targets a latent subpopulation</td>
</tr>
</tbody>
</table>
</section>
<section id="estimand-estimator-alignment" class="level2">
<h2 class="anchored" data-anchor-id="estimand-estimator-alignment">Estimand-Estimator Alignment</h2>
<p>For each estimand, multiple estimators are available—but not all of them estimate the quantity defined by the estimand. The table below summarises the correspondence.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>alignment_tbl <span class="ot">&lt;-</span> tibble<span class="sc">::</span><span class="fu">tribble</span>(</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span>Estimand, <span class="sc">~</span>Estimator, <span class="sc">~</span>Aligned, <span class="sc">~</span><span class="st">`</span><span class="at">Reason for misalignment</span><span class="st">`</span>,</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Treatment-policy"</span>, <span class="st">"LMTP SDR (static on/off)"</span>, <span class="st">"Yes"</span>,</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Targets marginal risk under baseline initiation; adjusts for censoring"</span>,</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Treatment-policy"</span>, <span class="st">"Cox naive (ignore switch)"</span>, <span class="st">"No"</span>,</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Conditional HR, not marginal RD; risk set altered by informative switching"</span>,</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Treatment-policy"</span>, <span class="st">"Cox censor-at-switch"</span>, <span class="st">"No"</span>,</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Removes high-risk subjects at switch; addresses a different estimand"</span>,</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Hypothetical no-switch"</span>, <span class="st">"LMTP SDR (no-switch intervention)"</span>, <span class="st">"Yes"</span>,</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Targets marginal risk without switching; adjusts for confounding"</span>,</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Hypothetical no-switch"</span>, <span class="st">"Cox censor-at-switch"</span>, <span class="st">"No"</span>,</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Assumes non-informative censoring; biased when switching is informative"</span>,</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>  <span class="st">"While-on-treatment"</span>, <span class="st">"LMTP SDR (censor model for switch)"</span>, <span class="st">"Yes"</span>,</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Upweights patients who remain on treatment despite high switch propensity"</span>,</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>  <span class="st">"While-on-treatment"</span>, <span class="st">"Cox censor-at-switch"</span>, <span class="st">"No"</span>,</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Non-informative censoring assumption violated"</span>,</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Composite"</span>, <span class="st">"Cox (composite outcome)"</span>, <span class="st">"Partial"</span>,</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">"HR for composite; conditional, not marginal"</span>,</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Principal stratum"</span>, <span class="st">"LMTP SDR (non-switchers)"</span>, <span class="st">"Approximate"</span>,</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Observed non-switchers are not the true principal stratum"</span></span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(alignment_tbl, <span class="at">format =</span> <span class="st">"pipe"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="tbl-alignment" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-alignment-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Estimand versus estimator alignment
</figcaption>
<div aria-describedby="tbl-alignment-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 15%">
<col style="width: 24%">
<col style="width: 8%">
<col style="width: 51%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Estimand</th>
<th style="text-align: left;">Estimator</th>
<th style="text-align: left;">Aligned</th>
<th style="text-align: left;">Reason for misalignment</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Treatment-policy</td>
<td style="text-align: left;">LMTP SDR (static on/off)</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Targets marginal risk under baseline initiation; adjusts for censoring</td>
</tr>
<tr class="even">
<td style="text-align: left;">Treatment-policy</td>
<td style="text-align: left;">Cox naive (ignore switch)</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Conditional HR, not marginal RD; risk set altered by informative switching</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Treatment-policy</td>
<td style="text-align: left;">Cox censor-at-switch</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Removes high-risk subjects at switch; addresses a different estimand</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hypothetical no-switch</td>
<td style="text-align: left;">LMTP SDR (no-switch intervention)</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Targets marginal risk without switching; adjusts for confounding</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hypothetical no-switch</td>
<td style="text-align: left;">Cox censor-at-switch</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Assumes non-informative censoring; biased when switching is informative</td>
</tr>
<tr class="even">
<td style="text-align: left;">While-on-treatment</td>
<td style="text-align: left;">LMTP SDR (censor model for switch)</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Upweights patients who remain on treatment despite high switch propensity</td>
</tr>
<tr class="odd">
<td style="text-align: left;">While-on-treatment</td>
<td style="text-align: left;">Cox censor-at-switch</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Non-informative censoring assumption violated</td>
</tr>
<tr class="even">
<td style="text-align: left;">Composite</td>
<td style="text-align: left;">Cox (composite outcome)</td>
<td style="text-align: left;">Partial</td>
<td style="text-align: left;">HR for composite; conditional, not marginal</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Principal stratum</td>
<td style="text-align: left;">LMTP SDR (non-switchers)</td>
<td style="text-align: left;">Approximate</td>
<td style="text-align: left;">Observed non-switchers are not the true principal stratum</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>When switching is informative, censoring at switch removes the highest-risk person-time from the active arm, attenuating the apparent treatment effect. The naive Cox model includes post-switch outcomes that may reflect the comparator rather than the active treatment. Neither approach targets the marginal risk contrast defined by the estimand. The LMTP sequentially doubly robust estimator addresses this by modelling the joint distribution of treatment, censoring, and outcome over time and integrating over confounders to produce marginal risk estimates.</p>
</section>
<section id="conventional-regression-analyses" class="level2">
<h2 class="anchored" data-anchor-id="conventional-regression-analyses">Conventional Regression Analyses</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>tau <span class="ot">&lt;-</span> <span class="dv">180</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>cox_naive <span class="ot">&lt;-</span> <span class="fu">fit_cox_naive</span>(dat, <span class="at">tau =</span> tau,</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>                           <span class="at">covars =</span> <span class="fu">c</span>(<span class="st">"age"</span>, <span class="st">"ckd"</span>, <span class="st">"cirrhosis"</span>,</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>                                      <span class="st">"diabetes"</span>, <span class="st">"heart_failure"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>cox_cs <span class="ot">&lt;-</span> <span class="fu">fit_cox_censor_switch</span>(dat, <span class="at">tau =</span> tau,</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>                                <span class="at">covars =</span> <span class="fu">c</span>(<span class="st">"age"</span>, <span class="st">"ckd"</span>, <span class="st">"cirrhosis"</span>,</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>                                           <span class="st">"diabetes"</span>, <span class="st">"heart_failure"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>cox_td <span class="ot">&lt;-</span> <span class="fu">fit_cox_td</span>(dat, <span class="at">tau =</span> tau,</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">covars =</span> <span class="fu">c</span>(<span class="st">"age"</span>, <span class="st">"ckd"</span>, <span class="st">"cirrhosis"</span>,</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"diabetes"</span>, <span class="st">"heart_failure"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>km_naive <span class="ot">&lt;-</span> <span class="fu">km_risk_at</span>(cox_naive<span class="sc">$</span>survfit, <span class="at">t =</span> tau)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>km_cs    <span class="ot">&lt;-</span> <span class="fu">km_risk_at</span>(cox_cs<span class="sc">$</span>survfit, <span class="at">t =</span> tau)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-cox-results" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cox-results-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Cox regression estimates from a single simulated dataset (N = 10,000)
</figcaption>
<div aria-describedby="tbl-cox-results-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Method</th>
<th style="text-align: right;">HR</th>
<th style="text-align: left;">HR 95% CI</th>
<th style="text-align: right;">KM Risk Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Naive Cox (ignore switch)</td>
<td style="text-align: right;">1.196</td>
<td style="text-align: left;">1.023–1.398</td>
<td style="text-align: right;">0.078</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cox censor at switch</td>
<td style="text-align: right;">1.179</td>
<td style="text-align: left;">1–1.39</td>
<td style="text-align: right;">0.070</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cox time-dependent treatment</td>
<td style="text-align: right;">1.155</td>
<td style="text-align: left;">0.99–1.347</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The naive Cox model uses only baseline treatment and ignores switching. Under non-proportional hazards, the resulting HR is a weighted average of time-varying hazard ratios with no clear marginal interpretation. Censoring at switch assumes non-informative censoring conditional on included covariates—an assumption violated when CKD drives both switching and the outcome. The time-dependent Cox model includes current treatment as a covariate, which estimates a conditional HR for current exposure, not the marginal risk contrast under a target intervention.</p>
<p>The unadjusted Kaplan-Meier risk differences reported above serve only as descriptive benchmarks.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Limitations of the hazard ratio as a causal parameter
</div>
</div>
<div class="callout-body-container callout-body">
<p>The Cox HR is problematic as an effect measure even in randomised trials. At later time points, differential event rates deplete high-risk subjects faster in one arm, so the groups being compared are no longer exchangeable (Stensrud et al.&nbsp;2019). The individual-level causal HR requires the untestable assumption that counterfactual survival times are conditionally independent (Martinussen 2022). Under non-proportional hazards, the Cox HR additionally depends on the censoring distribution (Rufibach 2018). Survival-function contrasts—risk differences, risk ratios, and restricted mean survival time—avoid these difficulties.</p>
</div>
</div>
</section>
<section id="estimation-with-lmtp" class="level2">
<h2 class="anchored" data-anchor-id="estimation-with-lmtp">Estimation with LMTP</h2>
<p>The <code>lmtp</code> package implements longitudinal modified treatment policies via the sequentially doubly robust (SDR) estimator. It targets a marginal risk under a specified intervention, adjusts for time-varying confounding, and provides doubly robust inference: the estimate is consistent if either the outcome model or the treatment/censoring model is correctly specified.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>lmtp_prep <span class="ot">&lt;-</span> <span class="fu">prepare_lmtp_data</span>(</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  dat, <span class="at">tau =</span> tau, <span class="at">bin_width =</span> <span class="dv">14</span>,</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">baseline =</span> <span class="fu">c</span>(<span class="st">"age"</span>, <span class="st">"sex_male"</span>, <span class="st">"ckd"</span>, <span class="st">"diabetes"</span>, <span class="st">"hypertension"</span>,</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>               <span class="st">"heart_failure"</span>)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We estimate marginal 180-day risks under static interventions: set <span class="math inline">\(A = 1\)</span> (active) or <span class="math inline">\(A = 0\)</span> (comparator) for all subjects. Follow-up is discretised into biweekly bins (13 time points).</p>
<!-- TODO(Joy): finalise the intervention function for the hypothetical
     no-switch estimand in the longitudinal LMTP setup. -->
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>lmtp_cache <span class="ot">&lt;-</span> <span class="fu">here</span>(<span class="st">"results"</span>, <span class="st">"lmtp_main.rds"</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="st">"Run R/run_cached_analyses.R first"</span> <span class="ot">=</span> <span class="fu">file.exists</span>(lmtp_cache))</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>lmtp_res <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(lmtp_cache)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>rd <span class="ot">&lt;-</span> lmtp_res<span class="sc">$</span>contrast_rd<span class="sc">$</span>estimates</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>rr <span class="ot">&lt;-</span> lmtp_res<span class="sc">$</span>contrast_rr<span class="sc">$</span>estimates</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-lmtp-results" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-lmtp-results-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: LMTP estimates from a single simulated dataset (N = 10,000)
</figcaption>
<div aria-describedby="tbl-lmtp-results-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Quantity</th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: left;">95% CI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Risk difference</td>
<td style="text-align: right;">-0.01589</td>
<td style="text-align: left;">-0.03944 to 0.00766</td>
</tr>
<tr class="even">
<td style="text-align: left;">Risk ratio</td>
<td style="text-align: right;">0.98160</td>
<td style="text-align: left;">0.9546 to 1.0087</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The Cox HR and the LMTP risk difference are not comparable as competing answers to the same question—they estimate different parameters on different scales. The concern is not which number is larger, but whether the estimator produces the quantity defined by the estimand.</p>
<section id="specification-notes" class="level3">
<h3 class="anchored" data-anchor-id="specification-notes">Specification notes</h3>
<p>The current analysis uses <code>SL.mean</code>, <code>SL.glm</code>, and <code>SL.bayesglm</code> with 2-fold cross-validation. For production analyses, the Super Learner library should include at minimum a parametric model, a penalised regression, and one flexible learner (Gruber et al.&nbsp;2022). The number of CV folds should be calibrated to the effective sample size. The SDR estimator respects model bounds (survival probabilities remain in <span class="math inline">\([0,1]\)</span>), an advantage over inverse-probability weighting in sparse data.</p>
<!-- TODO(Joy): benchmark runtime with a richer SL library. -->
</section>
</section>
<section id="known-truth-from-the-dgp" class="level2">
<h2 class="anchored" data-anchor-id="known-truth-from-the-dgp">Known Truth from the DGP</h2>
<p>Because we control the data-generating process, we can compute true marginal risks by generating large counterfactual datasets (500,000 subjects each under all-treated and all-control, with no dependent censoring).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>truth_cache <span class="ot">&lt;-</span> <span class="fu">here</span>(<span class="st">"results"</span>, <span class="st">"sim_results"</span>, <span class="st">"ground_truth.rds"</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="st">"Run R/run_cached_analyses.R first"</span> <span class="ot">=</span> <span class="fu">file.exists</span>(truth_cache))</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>truth_all <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(truth_cache)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>truth_summary <span class="ot">&lt;-</span> tibble<span class="sc">::</span><span class="fu">tibble</span>(</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">Estimand =</span> <span class="fu">c</span>(<span class="st">"Treatment-policy"</span>, <span class="st">"Hypothetical no-switch"</span>,</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>               <span class="st">"While-on-treatment"</span>, <span class="st">"Composite"</span>, <span class="st">"Principal stratum"</span>),</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">Risk (active)</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">c</span>(truth_all<span class="sc">$</span>treatment_policy<span class="sc">$</span>true_risk_1,</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>                       truth_all<span class="sc">$</span>no_switch<span class="sc">$</span>true_risk_1,</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>                       truth_all<span class="sc">$</span>while_on_treatment<span class="sc">$</span>true_risk_1,</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>                       truth_all<span class="sc">$</span>composite<span class="sc">$</span>true_risk_1,</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>                       truth_all<span class="sc">$</span>principal_stratum<span class="sc">$</span>true_risk_1),</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">Risk (comparator)</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">c</span>(truth_all<span class="sc">$</span>treatment_policy<span class="sc">$</span>true_risk_0,</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>                           truth_all<span class="sc">$</span>no_switch<span class="sc">$</span>true_risk_0,</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>                           truth_all<span class="sc">$</span>while_on_treatment<span class="sc">$</span>true_risk_0,</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>                           truth_all<span class="sc">$</span>composite<span class="sc">$</span>true_risk_0,</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>                           truth_all<span class="sc">$</span>principal_stratum<span class="sc">$</span>true_risk_0),</span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">RD =</span> <span class="fu">c</span>(truth_all<span class="sc">$</span>treatment_policy<span class="sc">$</span>true_rd,</span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>         truth_all<span class="sc">$</span>no_switch<span class="sc">$</span>true_rd,</span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>         truth_all<span class="sc">$</span>while_on_treatment<span class="sc">$</span>true_rd,</span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>         truth_all<span class="sc">$</span>composite<span class="sc">$</span>true_rd,</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>         truth_all<span class="sc">$</span>principal_stratum<span class="sc">$</span>true_rd),</span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">RR =</span> <span class="fu">c</span>(truth_all<span class="sc">$</span>treatment_policy<span class="sc">$</span>true_rr,</span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a>         truth_all<span class="sc">$</span>no_switch<span class="sc">$</span>true_rr,</span>
<span id="cb12-25"><a href="#cb12-25" aria-hidden="true" tabindex="-1"></a>         truth_all<span class="sc">$</span>while_on_treatment<span class="sc">$</span>true_rr,</span>
<span id="cb12-26"><a href="#cb12-26" aria-hidden="true" tabindex="-1"></a>         truth_all<span class="sc">$</span>composite<span class="sc">$</span>true_rr,</span>
<span id="cb12-27"><a href="#cb12-27" aria-hidden="true" tabindex="-1"></a>         truth_all<span class="sc">$</span>principal_stratum<span class="sc">$</span>true_rr),</span>
<span id="cb12-28"><a href="#cb12-28" aria-hidden="true" tabindex="-1"></a>  <span class="at">HR =</span> <span class="fu">c</span>(truth_all<span class="sc">$</span>treatment_policy<span class="sc">$</span>true_hr,</span>
<span id="cb12-29"><a href="#cb12-29" aria-hidden="true" tabindex="-1"></a>         truth_all<span class="sc">$</span>no_switch<span class="sc">$</span>true_hr,</span>
<span id="cb12-30"><a href="#cb12-30" aria-hidden="true" tabindex="-1"></a>         truth_all<span class="sc">$</span>while_on_treatment<span class="sc">$</span>true_hr,</span>
<span id="cb12-31"><a href="#cb12-31" aria-hidden="true" tabindex="-1"></a>         truth_all<span class="sc">$</span>composite<span class="sc">$</span>true_hr,</span>
<span id="cb12-32"><a href="#cb12-32" aria-hidden="true" tabindex="-1"></a>         truth_all<span class="sc">$</span>principal_stratum<span class="sc">$</span>true_hr)</span>
<span id="cb12-33"><a href="#cb12-33" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb12-34"><a href="#cb12-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-35"><a href="#cb12-35" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(truth_summary, <span class="at">digits =</span> <span class="dv">5</span>, <span class="at">format =</span> <span class="st">"pipe"</span>,</span>
<span id="cb12-36"><a href="#cb12-36" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"True 180-day risks by estimand (N = 500,000 per arm)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>True 180-day risks by estimand (N = 500,000 per arm)</caption>
<colgroup>
<col style="width: 28%">
<col style="width: 17%">
<col style="width: 22%">
<col style="width: 11%">
<col style="width: 10%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Estimand</th>
<th style="text-align: right;">Risk (active)</th>
<th style="text-align: right;">Risk (comparator)</th>
<th style="text-align: right;">RD</th>
<th style="text-align: right;">RR</th>
<th style="text-align: right;">HR</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Treatment-policy</td>
<td style="text-align: right;">0.14220</td>
<td style="text-align: right;">0.13541</td>
<td style="text-align: right;">0.00679</td>
<td style="text-align: right;">1.05013</td>
<td style="text-align: right;">1.06159</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hypothetical no-switch</td>
<td style="text-align: right;">0.13509</td>
<td style="text-align: right;">0.13555</td>
<td style="text-align: right;">-0.00045</td>
<td style="text-align: right;">0.99665</td>
<td style="text-align: right;">1.00583</td>
</tr>
<tr class="odd">
<td style="text-align: left;">While-on-treatment</td>
<td style="text-align: right;">0.13509</td>
<td style="text-align: right;">0.13555</td>
<td style="text-align: right;">-0.00045</td>
<td style="text-align: right;">0.99665</td>
<td style="text-align: right;">1.00583</td>
</tr>
<tr class="even">
<td style="text-align: left;">Composite</td>
<td style="text-align: right;">0.43189</td>
<td style="text-align: right;">0.28488</td>
<td style="text-align: right;">0.14701</td>
<td style="text-align: right;">1.51602</td>
<td style="text-align: right;">1.69547</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Principal stratum</td>
<td style="text-align: right;">0.13054</td>
<td style="text-align: right;">0.13063</td>
<td style="text-align: right;">-0.00009</td>
<td style="text-align: right;">0.99928</td>
<td style="text-align: right;">1.00840</td>
</tr>
</tbody>
</table>
</div>
</div>
<section id="why-the-estimands-differ" class="level3">
<h3 class="anchored" data-anchor-id="why-the-estimands-differ">Why the estimands differ</h3>
<p>The risk difference ranges from near zero to over 14 percentage points across the five strategies. This variation reflects genuinely different causal questions about the same drug, not a statistical artifact.</p>
<p>Under the treatment-policy strategy, the active drug increases risk (RD &gt; 0) because patients are followed regardless of switching. During the early period (HR = 1.25 before day 45), the active drug causes excess harm. Some patients subsequently switch to the comparator, reducing their later hazard, but the early harm has already accumulated.</p>
<p>Under the hypothetical no-switch strategy, the risk difference is approximately zero. Without switching, the early harm (HR = 1.25) is offset by the late protective effect (HR = 0.70) over the full 180-day window. The while-on-treatment truth is numerically identical because, under counterfactual all-treated or all-control conditions, nobody switches.</p>
<p>The composite estimand produces the largest risk difference because the active drug causes substantially more switching. The composite event rate in the active arm is driven primarily by differential switching rates, not differential renal failure.</p>
<p>Among the approximately 19% of patients who constitute the principal stratum (never-switchers under either treatment), the risk difference is near zero. These patients tend to be lower-risk (without CKD), for whom the treatment effect is small.</p>
</section>
</section>
<section id="sec-support" class="level2">
<h2 class="anchored" data-anchor-id="sec-support">Data Support Diagnostics</h2>
<p>Even when a causal estimand is well-defined and identifiable in principle, estimation can fail if the data lack empirical support. Positivity requires that, within every stratum of measured confounders, there is a nonzero probability of receiving each treatment and of not being censored. In longitudinal settings, sequential positivity requires that the cumulative product of treatment and censoring probabilities remains bounded away from zero across all time points (Gruber et al.&nbsp;2022).</p>
<p>We examine three scenarios that vary switching intensity while holding the treatment assignment mechanism fixed.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">101</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>dat_good <span class="ot">&lt;-</span> <span class="fu">generate_hep_data</span>(</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">N =</span> <span class="dv">5000</span>, <span class="at">np_hazard =</span> <span class="cn">TRUE</span>, <span class="at">dep_censor =</span> <span class="cn">TRUE</span>,</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">complexity =</span> <span class="cn">TRUE</span>, <span class="at">policy =</span> <span class="st">"treatment_policy"</span>, <span class="at">seed =</span> <span class="dv">101</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">102</span>)</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>dat_strained <span class="ot">&lt;-</span> <span class="fu">generate_hep_data</span>(</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">N =</span> <span class="dv">5000</span>, <span class="at">np_hazard =</span> <span class="cn">TRUE</span>, <span class="at">dep_censor =</span> <span class="cn">TRUE</span>,</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">complexity =</span> <span class="cn">TRUE</span>, <span class="at">policy =</span> <span class="st">"treatment_policy"</span>,</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">gamma_A =</span> <span class="fl">1.5</span>, <span class="at">gamma_ckd =</span> <span class="fl">1.2</span>, <span class="at">lambda_sw0 =</span> <span class="fl">5e-3</span>,</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">seed =</span> <span class="dv">102</span></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">103</span>)</span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>dat_poor <span class="ot">&lt;-</span> <span class="fu">generate_hep_data</span>(</span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">N =</span> <span class="dv">5000</span>, <span class="at">np_hazard =</span> <span class="cn">TRUE</span>, <span class="at">dep_censor =</span> <span class="cn">TRUE</span>,</span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">complexity =</span> <span class="cn">TRUE</span>, <span class="at">policy =</span> <span class="st">"treatment_policy"</span>,</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">gamma_A =</span> <span class="fl">2.5</span>, <span class="at">gamma_ckd =</span> <span class="fl">2.0</span>, <span class="at">lambda_sw0 =</span> <span class="fl">1e-2</span>,</span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">seed =</span> <span class="dv">103</span></span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Because treatment assignment parameters are held constant, treatment propensity scores are identical across scenarios. The relevant diagnostic is the distribution of predicted switching probabilities.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>scenario_list <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"1. Good support"</span> <span class="ot">=</span> dat_good,</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"2. Strained support"</span> <span class="ot">=</span> dat_strained,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"3. Poor support"</span> <span class="ot">=</span> dat_poor</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>support_plots <span class="ot">&lt;-</span> <span class="fu">plot_support_scenarios</span>(scenario_list)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>support_plots<span class="sc">$</span>by_treatment</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-support-switch" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-support-switch-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="draft-estimands-results-outline_files/figure-html/fig-support-switch-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-support-switch-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Predicted switching probability by treatment arm across three scenarios.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>support_plots<span class="sc">$</span>by_ckd</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-support-ckd" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-support-ckd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="draft-estimands-results-outline_files/figure-html/fig-support-ckd-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-support-ckd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Switching probability by CKD status across scenarios.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>support_tbl <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize_support</span>(dat_good, <span class="st">"Good support"</span>),</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize_support</span>(dat_strained, <span class="st">"Strained support"</span>),</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize_support</span>(dat_poor, <span class="st">"Poor support"</span>)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(support_tbl, <span class="at">digits =</span> <span class="dv">3</span>, <span class="at">format =</span> <span class="st">"pipe"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="tbl-support" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-support-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Support diagnostic summary
</figcaption>
<div aria-describedby="tbl-support-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 12%">
<col style="width: 3%">
<col style="width: 9%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 11%">
<col style="width: 12%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">scenario</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">switch_rate</th>
<th style="text-align: right;">ps_near_0</th>
<th style="text-align: right;">ps_near_1</th>
<th style="text-align: right;">ps_violation</th>
<th style="text-align: right;">p_switch_ckd</th>
<th style="text-align: right;">p_switch_nockd</th>
<th style="text-align: right;">natural_sof_nosw</th>
<th style="text-align: right;">natural_nonsof_nosw</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Good support</td>
<td style="text-align: right;">5000</td>
<td style="text-align: right;">0.119</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.198</td>
<td style="text-align: right;">0.112</td>
<td style="text-align: right;">0.315</td>
<td style="text-align: right;">0.566</td>
</tr>
<tr class="even">
<td style="text-align: left;">Strained support</td>
<td style="text-align: right;">5000</td>
<td style="text-align: right;">0.472</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.718</td>
<td style="text-align: right;">0.450</td>
<td style="text-align: right;">0.123</td>
<td style="text-align: right;">0.405</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Poor support</td>
<td style="text-align: right;">5000</td>
<td style="text-align: right;">0.655</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.907</td>
<td style="text-align: right;">0.631</td>
<td style="text-align: right;">0.035</td>
<td style="text-align: right;">0.310</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>support_cache <span class="ot">&lt;-</span> <span class="fu">here</span>(<span class="st">"results"</span>, <span class="st">"support_estimation.rds"</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="st">"Run R/run_cached_analyses.R first"</span> <span class="ot">=</span> <span class="fu">file.exists</span>(support_cache))</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>support_results <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(support_cache)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(support_results, <span class="at">digits =</span> <span class="dv">4</span>, <span class="at">format =</span> <span class="st">"pipe"</span>,</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Estimation results across support scenarios"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Estimation results across support scenarios</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Scenario</th>
<th style="text-align: right;">Cox naive HR</th>
<th style="text-align: right;">Cox censor HR</th>
<th style="text-align: right;">LMTP RD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Good support</td>
<td style="text-align: right;">1.1473</td>
<td style="text-align: right;">1.1607</td>
<td style="text-align: right;">-0.0212</td>
</tr>
<tr class="even">
<td style="text-align: left;">Strained support</td>
<td style="text-align: right;">1.1805</td>
<td style="text-align: right;">1.1997</td>
<td style="text-align: right;">-0.0343</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Poor support</td>
<td style="text-align: right;">1.3887</td>
<td style="text-align: right;">2.2729</td>
<td style="text-align: right;">-0.0575</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Under good support (~12% switching), the three estimators produce stable estimates. As switching intensifies, the censor-at-switch Cox HR diverges from the naive HR (2.27 vs 1.39 under poor support), because censoring removes a large, non-random fraction of the active arm. LMTP estimates show increasing bias and wider confidence intervals as the censoring model must extrapolate into regions with limited data.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Identification versus estimation
</div>
</div>
<div class="callout-body-container callout-body">
<p>A well-defined, identifiable estimand does not guarantee reliable estimation. If few subjects in certain strata follow the target intervention, support diagnostics should be examined before interpreting any estimate.</p>
</div>
</div>
</section>
<section id="repeated-simulation-study" class="level2">
<h2 class="anchored" data-anchor-id="repeated-simulation-study">Repeated Simulation Study</h2>
<p>We assess estimator performance over 20 repeated samples (N = 10,000 each) from the DGP, across all five estimands. For each iteration, we fit Cox naive, Cox censor-at-switch, and LMTP SDR, and compare the resulting risk differences and hazard ratios to the known truth.</p>
<!-- TODO(Joy): increase to 200+ iterations for production. -->
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="fu">here</span>(<span class="st">"R"</span>, <span class="st">"run_simulations.R"</span>))</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>sim_cache <span class="ot">&lt;-</span> <span class="fu">here</span>(<span class="st">"results"</span>, <span class="st">"sim_study_main.rds"</span>)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="st">"Run R/run_cached_analyses.R first"</span> <span class="ot">=</span> <span class="fu">file.exists</span>(sim_cache))</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>sim_results <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(sim_cache)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>estimand_labels <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">treatment_policy   =</span> <span class="st">"Treatment-policy"</span>,</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">no_switch          =</span> <span class="st">"Hypothetical no-switch"</span>,</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">while_on_treatment =</span> <span class="st">"While-on-treatment"</span>,</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">composite          =</span> <span class="st">"Composite"</span>,</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">principal_stratum  =</span> <span class="st">"Principal stratum"</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>sim_summaries <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="fu">names</span>(truth_all), <span class="cf">function</span>(est) {</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="sc">!</span>est <span class="sc">%in%</span> sim_results<span class="sc">$</span>estimand) <span class="fu">return</span>(<span class="cn">NULL</span>)</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>  sub <span class="ot">&lt;-</span> sim_results <span class="sc">%&gt;%</span> <span class="fu">filter</span>(estimand <span class="sc">==</span> est)</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>  s <span class="ot">&lt;-</span> <span class="fu">summarize_simulation</span>(sub,</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>         <span class="at">truth_rd =</span> truth_all[[est]]<span class="sc">$</span>true_rd,</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>         <span class="at">truth_rr =</span> truth_all[[est]]<span class="sc">$</span>true_rr,</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>         <span class="at">truth_hr =</span> truth_all[[est]]<span class="sc">$</span>true_hr)</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>  s<span class="sc">$</span>estimand_label <span class="ot">&lt;-</span> estimand_labels[est]</span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>  s</span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>}) <span class="sc">%&gt;%</span> <span class="fu">bind_rows</span>()</span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Clean table: replace NaN with NA for display</span></span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a>sim_display <span class="ot">&lt;-</span> sim_summaries <span class="sc">%&gt;%</span></span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(estimand_label, method, n_converged,</span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a>         mean_hr, bias_hr, mean_rd, bias_rd,</span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a>         mean_rr, bias_rr, coverage_rd) <span class="sc">%&gt;%</span></span>
<span id="cb19-25"><a href="#cb19-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">Estimand =</span> estimand_label, <span class="at">Method =</span> method) <span class="sc">%&gt;%</span></span>
<span id="cb19-26"><a href="#cb19-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), <span class="sc">~</span> <span class="fu">ifelse</span>(<span class="fu">is.nan</span>(.), <span class="cn">NA</span>, .)))</span>
<span id="cb19-27"><a href="#cb19-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-28"><a href="#cb19-28" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(sim_display, <span class="at">digits =</span> <span class="dv">4</span>, <span class="at">format =</span> <span class="st">"pipe"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="tbl-sim-all" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-sim-all-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Simulation results by estimand (20 iterations, N = 10,000)
</figcaption>
<div aria-describedby="tbl-sim-all-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 19%">
<col style="width: 20%">
<col style="width: 10%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Estimand</th>
<th style="text-align: left;">Method</th>
<th style="text-align: right;">n_converged</th>
<th style="text-align: right;">mean_hr</th>
<th style="text-align: right;">bias_hr</th>
<th style="text-align: right;">mean_rd</th>
<th style="text-align: right;">bias_rd</th>
<th style="text-align: right;">mean_rr</th>
<th style="text-align: right;">bias_rr</th>
<th style="text-align: right;">coverage_rd</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Treatment-policy</td>
<td style="text-align: left;">Cox censor-at-switch</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">1.1926</td>
<td style="text-align: right;">0.1310</td>
<td style="text-align: right;">0.0764</td>
<td style="text-align: right;">0.0696</td>
<td style="text-align: right;">1.7543</td>
<td style="text-align: right;">0.7042</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Treatment-policy</td>
<td style="text-align: left;">Cox naive</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">1.2063</td>
<td style="text-align: right;">0.1447</td>
<td style="text-align: right;">0.0859</td>
<td style="text-align: right;">0.0791</td>
<td style="text-align: right;">1.8502</td>
<td style="text-align: right;">0.8001</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Treatment-policy</td>
<td style="text-align: left;">LMTP SDR</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">-0.0207</td>
<td style="text-align: right;">-0.0275</td>
<td style="text-align: right;">0.9762</td>
<td style="text-align: right;">-0.0740</td>
<td style="text-align: right;">0.35</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hypothetical no-switch</td>
<td style="text-align: left;">Cox censor-at-switch</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">1.1919</td>
<td style="text-align: right;">0.1861</td>
<td style="text-align: right;">0.0803</td>
<td style="text-align: right;">0.0807</td>
<td style="text-align: right;">1.8004</td>
<td style="text-align: right;">0.8037</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hypothetical no-switch</td>
<td style="text-align: left;">Cox naive</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">1.1919</td>
<td style="text-align: right;">0.1861</td>
<td style="text-align: right;">0.0803</td>
<td style="text-align: right;">0.0807</td>
<td style="text-align: right;">1.8004</td>
<td style="text-align: right;">0.8037</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hypothetical no-switch</td>
<td style="text-align: left;">LMTP SDR</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">-0.0145</td>
<td style="text-align: right;">-0.0140</td>
<td style="text-align: right;">0.9834</td>
<td style="text-align: right;">-0.0133</td>
<td style="text-align: right;">0.75</td>
</tr>
<tr class="odd">
<td style="text-align: left;">While-on-treatment</td>
<td style="text-align: left;">Cox censor-at-switch</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">1.1926</td>
<td style="text-align: right;">0.1868</td>
<td style="text-align: right;">0.0764</td>
<td style="text-align: right;">0.0769</td>
<td style="text-align: right;">1.7543</td>
<td style="text-align: right;">0.7577</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">While-on-treatment</td>
<td style="text-align: left;">Cox naive</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">1.1926</td>
<td style="text-align: right;">0.1868</td>
<td style="text-align: right;">0.0764</td>
<td style="text-align: right;">0.0769</td>
<td style="text-align: right;">1.7543</td>
<td style="text-align: right;">0.7577</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">While-on-treatment</td>
<td style="text-align: left;">LMTP SDR</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">-0.0147</td>
<td style="text-align: right;">-0.0143</td>
<td style="text-align: right;">0.9831</td>
<td style="text-align: right;">-0.0136</td>
<td style="text-align: right;">0.85</td>
</tr>
<tr class="even">
<td style="text-align: left;">Composite</td>
<td style="text-align: left;">Cox censor-at-switch</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">1.7947</td>
<td style="text-align: right;">0.0993</td>
<td style="text-align: right;">0.2068</td>
<td style="text-align: right;">0.0598</td>
<td style="text-align: right;">1.8097</td>
<td style="text-align: right;">0.2937</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Composite</td>
<td style="text-align: left;">Cox naive</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">1.7947</td>
<td style="text-align: right;">0.0993</td>
<td style="text-align: right;">0.2068</td>
<td style="text-align: right;">0.0598</td>
<td style="text-align: right;">1.8097</td>
<td style="text-align: right;">0.2937</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Composite</td>
<td style="text-align: left;">LMTP SDR</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">-0.1624</td>
<td style="text-align: right;">-0.3094</td>
<td style="text-align: right;">0.7707</td>
<td style="text-align: right;">-0.7453</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Principal stratum</td>
<td style="text-align: left;">Cox censor-at-switch</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">1.1926</td>
<td style="text-align: right;">0.1842</td>
<td style="text-align: right;">0.0764</td>
<td style="text-align: right;">0.0765</td>
<td style="text-align: right;">1.7543</td>
<td style="text-align: right;">0.7550</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Principal stratum</td>
<td style="text-align: left;">Cox naive</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">1.2063</td>
<td style="text-align: right;">0.1979</td>
<td style="text-align: right;">0.0859</td>
<td style="text-align: right;">0.0860</td>
<td style="text-align: right;">1.8502</td>
<td style="text-align: right;">0.8509</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Principal stratum</td>
<td style="text-align: left;">LMTP SDR (non-switchers)</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">-0.0261</td>
<td style="text-align: right;">-0.0261</td>
<td style="text-align: right;">0.9695</td>
<td style="text-align: right;">-0.0298</td>
<td style="text-align: right;">0.55</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot only risk differences (not HRs) for clarity</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>sim_plot_rd <span class="ot">&lt;-</span> sim_results <span class="sc">%&gt;%</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(converged, <span class="sc">!</span><span class="fu">is.na</span>(risk_diff)) <span class="sc">%&gt;%</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">estimand_label =</span> estimand_labels[estimand])</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>truth_lines <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">estimand_label =</span> <span class="fu">unname</span>(estimand_labels[<span class="fu">names</span>(truth_all)]),</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">xint =</span> <span class="fu">sapply</span>(truth_all, <span class="cf">function</span>(x) x<span class="sc">$</span>true_rd)</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sim_plot_rd, <span class="fu">aes</span>(<span class="at">x =</span> risk_diff, <span class="at">fill =</span> method)) <span class="sc">+</span></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>, <span class="at">bins =</span> <span class="dv">20</span>, <span class="at">position =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> estimand_label, <span class="at">scales =</span> <span class="st">"free"</span>, <span class="at">ncol =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">data =</span> truth_lines,</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>             <span class="fu">aes</span>(<span class="at">xintercept =</span> xint), <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Risk Difference"</span>, <span class="at">y =</span> <span class="st">"Count"</span>, <span class="at">fill =</span> <span class="st">"Method"</span>) <span class="sc">+</span></span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">11</span>) <span class="sc">+</span></span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-sim-performance" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sim-performance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="draft-estimands-results-outline_files/figure-html/fig-sim-performance-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="864">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sim-performance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Distribution of risk difference estimates across iterations. Red dashed line indicates true RD.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="interpretation" class="level2">
<h2 class="anchored" data-anchor-id="interpretation">Interpretation</h2>
<p>Across all five estimands, the unadjusted Cox hazard ratios and Kaplan-Meier risk differences are substantially biased, with 0% coverage in every case. CKD confounds both treatment assignment and the outcome; the resulting bias inflates the apparent treatment effect by roughly an order of magnitude relative to the true risk difference for the non-composite estimands.</p>
<p>The Cox naive and censor-at-switch estimators differ under the treatment-policy estimand (mean HR 1.21 vs 1.19), confirming that censoring at switch attenuates the estimate by selectively removing high-risk person-time. Under no-switch data, the two are identical, as expected.</p>
<p>LMTP produces less biased estimates for most estimands. For the no-switch and while-on-treatment estimands (near-null true effects), coverage reaches 75–85%. For the treatment-policy estimand (true RD = +0.007), coverage is lower at 35%, reflecting a residual negative bias of approximately -0.03 that likely arises from the combination of biweekly time bins, a limited Super Learner library, and a sparse event rate (~8%).</p>
<p>The composite LMTP estimate is severely biased (mean RD = -0.16 vs truth = +0.15). This is a specification error, not a failure of the LMTP framework: the static-intervention analysis adjusts away switching through its censoring model, which is the opposite of what the composite estimand requires (switching should be counted as an event, not modelled as censoring). The LMTP analysis restricted to observed non-switchers provides a rough approximation of the principal stratum (55% coverage), though the approximation is imperfect because observed non-switchers are not the same as the latent never-switcher stratum.</p>
</section>
<section id="sensitivity-to-unmeasured-confounding" class="level2">
<h2 class="anchored" data-anchor-id="sensitivity-to-unmeasured-confounding">Sensitivity to Unmeasured Confounding</h2>
<p>Even with a well-specified estimator and adequate support, causal interpretation requires no unmeasured confounding. The causal gap <span class="math inline">\(\delta = \psi_{\text{stat}} - \psi_{\text{causal}}\)</span> quantifies residual confounding from unmeasured common causes. The G-value (Gruber et al.&nbsp;2024)—the minimum causal gap needed to shift the confidence interval to include the null—provides a useful sensitivity diagnostic. If the G-value is large relative to the measured confounding adjustment, the finding is robust; if small, modest unmeasured confounding could nullify the result.</p>
<p>This tutorial does not implement a full sensitivity analysis.</p>
<!-- TODO(Joy): implement a nonparametric sensitivity analysis function and
     add a worked example to the simulation study. -->
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<p>Three observations emerge from this simulation study. First, conventional Cox regression analyses—whether ignoring switching, censoring at switch, or including time-dependent treatment—produce biased estimates of every estimand examined here, primarily because of uncontrolled confounding. Second, LMTP substantially reduces this bias for estimands that match its intervention specification (treatment-policy, hypothetical no-switch, while-on-treatment), but residual bias remains under the current specification. Third, the same drug yields markedly different risk differences depending on how switching is handled—from near zero (hypothetical, principal stratum) to +0.15 (composite)—and the choice of estimand strategy should be driven by the clinical question, not by computational convenience.</p>
<p>These results also highlight two limitations. LMTP performance depends on the temporal resolution of time bins and the flexibility of the Super Learner library; the biweekly bins and minimal learner set used here are likely insufficient for production analyses. And when the intervention specification does not match the estimand (as with the composite), even a well-designed estimator framework produces wrong answers. Transparent reporting of estimand, assumptions, diagnostics, and estimator specification is essential.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<ul>
<li>ICH E9(R1) Addendum (2019). Addendum on estimands and sensitivity analyses in clinical trials.</li>
<li>Williams N, Diaz I (2023). lmtp: Non-parametric causal effects of feasible interventions based on modified treatment policies. R package.</li>
<li>van der Laan MJ, Rose S (2011). <em>Targeted Learning.</em> Springer.</li>
<li>Hernan MA, Robins JM (2020). <em>Causal Inference: What If.</em> Chapman &amp; Hall.</li>
<li>Dang LE, Tarp JM, Abrahamsen B, et al.&nbsp;(2023). A causal roadmap for generating high-quality real-world evidence. <em>J Clin Transl Sci.</em></li>
<li>Gruber S, Lee H, Phillips R, Ho M, van der Laan MJ (2022). Developing a targeted learning-based statistical analysis plan. <em>Stat Biopharm Res.</em></li>
<li>Gruber S, Phillips RV, Lee H, van der Laan MJ (2024). Targeted learning: toward a future informed by real-world evidence. <em>Stat Biopharm Res.</em></li>
<li>Chen RC, Rosenblum M, van der Laan MJ, Gruber S (2023). Beyond the Cox hazard ratio. <em>Clinical Trials.</em></li>
<li>Martinussen T (2022). Causality and the Cox regression model. <em>Annu Rev Stat Appl.</em></li>
<li>Stensrud MJ, Aalen JM, Aalen OO, Valberg M (2019). Limitations of hazard ratios in clinical trials. <em>Eur Heart J.</em></li>
<li>Rufibach K (2019). Treatment effect quantification for time-to-event endpoints. <em>Pharm Stat.</em></li>
<li>Petersen ML (2014). Applying a causal road map in settings with time-dependent confounding. <em>Epidemiology.</em></li>
</ul>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>